name = "lottery-prophet"
pages_build_output_dir = "public"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "lottery-db"
database_id = "44a4bb2b-3d97-41a2-a440-6057016e05d4" # 请在此处替换你的 D1 数据库 ID

[vars]
# 这里的变量建议在 Cloudflare Pages 后台 (Settings -> Environment variables) 配置
# 这样更安全，避免 Token 泄露到代码库中
# TELEGRAM_TOKEN = "你的机器人Token"
# ADMIN_CHAT_ID = "你的管理员ID"
# URL_HK = "API地址"
# URL_MO_NEW = "API地址"
# URL_MO_OLD = "API地址"
# URL_MO_OLD_2230 = "API地址"
